### ISSUE TITLE
Does this support pod or carthage?

### ISSUE THREAD

**Issue by Naixor** [IBM-Swift/swift-html-entities#16]

**Comment by youming-lin** [comment]
Hi @Naixor 

Currently, only Swift Package Manager (SPM) is officially supported; however, I believe Carthage supports GitHub repos as they are, so you should be able to add `github "IBM-Swift/swift-html-entities"` to your project's `Cartfile` and pull in the code via `carthage update`.

**Comment by youming-lin** [comment]
@Naixor
I've added CocoaPod support in the latest release: https://github.com/IBM-Swift/swift-html-entities/releases/tag/3.0.4

Instructions on installing this package via CocoaPod and Carthage have been added to the README. Feel free to open a new issue if you are still having issues downloading this package via CocoaPod or Carthage.
