### ISSUE TITLE
Renamed HTMLConstants

### ISSUE THREAD

**Issue by dimitris-c** [IBM-Swift/swift-html-entities#25]
I believe the naming of `HTMLConstants` was better. Using this library without Swift Package Manager will cause issues if an already existing struct named Constants exists within the app.

**Comment by youming-lin** [comment]
@dimitris-c Do you mean to rename the file from `Constants.swift` to `HTMLConstants.swift`? I didn't know that file names could clash with struct names.

**Comment by dimitris-c** [comment]
@youming-lin This happens because I have copied the source files in my project as I'm not using Swift Package Manager. It may be nice to see Cocoapods support.

**Comment by youming-lin** [comment]
@dimitris-c 
I'm brand new to Cocoapods, having only used SPM for server-side Swift development, but I've gone ahead and added a new experimental branch with pod support here: https://github.com/IBM-Swift/swift-html-entities/tree/pod_support

Can you try it out and see if it works with your Podfile? I tested locally with this line in my `Podfile` and was able to download it via `pod install`:
```
pod 'HTMLEntities', :git => 'https://github.com/IBM-Swift/swift-html-entities.git', :branch => 'pod_support'
```

**Comment by dimitris-c** [comment]
@youming-lin Yes, it seems to be working fine!

**Comment by youming-lin** [comment]
@dimitris-c I've merged the podspec change and tagged a new release: https://github.com/IBM-Swift/swift-html-entities/releases/tag/3.0.4

Feel free to open a new issue if you are still having issues with CocoaPods. Note that I haven't uploaded the podspec to the official Pod spec repo so you'll have to use the GitHub URL (similar to how SPM works).
