### ISSUE TITLE
Version not set in xcodeproj: Can't upload to App Store using Carthage

### ISSUE THREAD

**Issue by rzulkoski** [IBM-Swift/swift-html-entities#38]
When attempting to upload to the App Store while including HTMLEntities as a Carthage dependency, the iTunes Connect complains with the following:

`ERROR ITMS-90056: "This bundle Payload/Storefront.app/Frameworks/HTMLEntities.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."`

I would assume that the `CFBundleShortVersionString` would also be required if it's not already set.

**Comment by youming-lin** [comment]
I merged this fix yesterday: https://github.com/IBM-Swift/swift-html-entities/pull/37

Can you try again with the latest release, 3.0.9?

**Comment by rzulkoski** [comment]
My bad, didn't realize I wasn't on the latest version. Closing the issue. Thanks!
