### ISSUE TITLE
This application’s bundle identifier does not match its code signing identifier.

### ISSUE THREAD

**Issue by sixty8** [IBM-Swift/swift-html-entities#40]
installing with Carthage
X-Code 9
Swift 4

simulator: no errors
device (iphone 6 - ipad air 2 - iphone 7): This application’s bundle identifier does not match its code signing identifier.

**Comment by youming-lin** [comment]
Seems like it's due to `Carthage`: https://stackoverflow.com/questions/34642165/this-applications-bundle-identifier-does-not-match-its-code-signing-identifier

Can you check if the fix in that answer fixes your issue?

**Comment by sixty8** [comment]
No, I already did this, but i always get the same error.
The error goes away when i remove this library.
