### ISSUE TITLE
No such module 'HTMLEntities'

### ISSUE THREAD

**Issue by TCOA** [IBM-Swift/swift-html-entities#41]
podfile (as per instructions)
`pod 'HTMLEntities', :git => 'https://github.com/IBM-Swift/swift-html-entities.git'`

running pod install shows
`Installing HTMLEntities (3.0.4)`

yet, when doing 
`import HTMLEntities`

I get
`No such module 'HTMLEntities'`

**Comment by youming-lin** [comment]
Have you tried adding the `HTMLEntities` framework to your Xcode project's Linked Frameworks and Libraries section?

**Comment by TCOA** [comment]
I finally got it to work (and it works great now) - I think it was something in Xcode (not surprising...) - as I recall, I wound up doing a Clean and even exiting/restarting Xcode - i.e., stupid things you should not have to do, but seems you must often enough with such a 'core' product....
