### ISSUE TITLE
New tag, please

### ISSUE THREAD

**Issue by twostraws** [IBM-Swift/swift-html-entities#43]
Swift 4 "characters" warnings were fixed 6 months ago, but the most recent tag (3.0.9) pre-dates that so we all get the warnings still. Could you please add a 3.0.10 tag or similar?

**Comment by ianpartridge** [comment]
@youming-lin do you want to tag, or shall I do it?

**Comment by youming-lin** [comment]
@ianpartridge I'll defer to you to tag a new version. Update [this line](https://github.com/IBM-Swift/swift-html-entities/blob/master/HTMLEntities.podspec#L19) as well so that `pod` can pick up the latest release.

**Comment by ianpartridge** [comment]
I've asked @EnriqueL8 to do it as I'm out from today.  I guess the podspec should be updated before the repo is tagged?

**Comment by youming-lin** [comment]
It worked for me post-tag, but it probably doesn't hurt to update before tagging so the update is included in the release.

**Comment by EnriqueL8** [comment]
The PR is up [here](https://github.com/IBM-Swift/swift-html-entities/pull/44), waiting for @youming-lin 's review
