### ISSUE TITLE
SDK does not finish archive in Xcode 10.2/Swift 4.2

### ISSUE THREAD

**Issue by erikkerber** [IBM-Swift/swift-html-entities#50]
## Description

When archiving HTMLEntities, Xcode does not finish compiling in a reasonable amount of time. In my longest run, I terminated it after 550 seconds. The indirect cause of this is Swift code optimization being enabled for "Release" builds. Related, the project takes 30 seconds to compile without code optimization despite being just 4 files.

Through trial-and-error, I determined that the large dictionary literal definitions in **Constants.swift** are the direct cause.

https://github.com/IBM-Swift/swift-html-entities/blob/master/Sources/HTMLEntities/Constants.swift#L161

https://github.com/IBM-Swift/swift-html-entities/blob/master/Sources/HTMLEntities/Constants.swift#L432

## Potential stop-gap

I believe that modifying the definitions to be lazy-constructed through a series of appends would allow the library to be compiled with optimizations turned on.

## Swift Source Compatibility

Since the code is not necessarily incorrect, this may be a candidate to add to the Swift Source Compatibility list: https://swift.org/source-compatibility/#adding-projects

Though, admittedly, the ship has already sailed for the most recent release of the tools.

**Comment by ianpartridge** [comment]
Hi, thanks for raising this. Would you mind prototyping the lazy construction of the dictionaries and seeing if this does indeed fix the problem? If so we would be happy to take this change.

**Comment by rzulkoski** [comment]
@eskerber Another idea might be to store those maps in JSON, and then lazily decode the maps.

**Comment by erikkerber** [comment]
I tried a few techniques:

* Break the literals up into several smaller dictionaries, and merge them.
* Convert String literals into Unicode.Scalar representation: (i.e. `Character(Unicode.Scalar(0x2A31)!)`)

Neither helped the compiler crawl out from the massive amounts of literals defined in that file, _but_ technique 2 _does indeed finish_ after... hold onto your butts... 256 seconds on my 6-core i7.

As to @rzulkoski's suggestion, I'm sure one could get creative on getting these mappings into memory.  Not sure how much time I have to experiment but from my end as long as it finishes at all, we're probably good. We use Carthage so developers will unfortunately have 1 sludge of a bootstrap in front of them, but it should be a one-time pain point.

**Comment by erikkerber** [comment]
I have submitted a PR which helps the issue, but does not cure it. It does enough to unblock its usage as long as your development is able to cache archived builds of the framework.

(In other words - I don't think anyone wants to add 4 minutes to their release CI/CD pipeline 😄)

**Comment by erikkerber** [comment]
https://bugs.swift.org/browse/SR-10209

**Comment by ianpartridge** [comment]
Thanks for opening the PR, and raising the Swift bug! We'll take a look ASAP.
