### ISSUE TITLE
Documentation page gives 404

### ISSUE THREAD

**Issue by christiancamaisa** [IBM-Swift/swift-html-entities#60]
The GitHub pages site @ [https://ibm-swift.github.io/swift-html-entities/](https://ibm-swift.github.io/swift-html-entities/ ) returns a 404 error.

**Comment by futurejones** [comment]
Hi @ccamaisa 
The links for all the Kitura sites are in the process of being updated.

You can access the docs at https://kitura.github.io/swift-html-entities/

**Comment by mbarnach** [comment]
@ccamaisa Where did you find that URL, so we can update it? Thanks.

**Comment by futurejones** [comment]
@mbarnach all the Kitura repos that have docs as github pages have links on their main pages. This is on the right just under `About`. e.g. on this repo https://ibm-swift.github.io/swift-html-entities/
This is not in code and has to be manually changed in the repos settings pages.

**Comment by futurejones** [comment]
This is changed using the `gear` icon to the right of `About`

**Comment by mbarnach** [comment]
I see. Unfortunately, I don't have write access to this repo. @dannys42 Could you either grant me access or do it? I assume many Kitura repository have the issue. @futurejones thanks!

**Comment by dannys42** [comment]
There weren't many repos that needed fixing, but they should all be fixed now.
