### ISSUE TITLE
Support less-aggressive character encoding

### ISSUE THREAD

**Issue by twostraws** [IBM-Swift/swift-html-entities#9]
Right now swift-html-entities aggressively encodes everything, even when it's perfectly acceptable inside HTML. For example, line breaks become `&NewLine;`.

HE, the library this is based on, has an `escape()` function that "takes a string of text and escapes it for use in text contexts in XML or HTML documents… only the following characters are escaped: &, <, >, ", ', and `." PHP has a [htmlspecialchars](http://php.net/manual/en/function.htmlspecialchars.php) function that does something similar, although it ignores backticks.

Is it possible to get something similar here?

**Comment by youming-lin** [comment]
@twostraws Based on my observation, by default `he` only escapes `&`, `<`, `>`, `"`, `'`, and `` ` `` in the ASCII space. Are these six characters enough?

**Comment by twostraws** [comment]
Yes, I think that ought to be safe for general rendering of content.

**Comment by youming-lin** [comment]
Code has been updated to skip the non-printing ASCII characters when escaping in #11.

Along with additional changes to the package to bring it more in line with `he`'s encode options, a new [version 3.0.0](https://github.com/IBM-Swift/swift-html-entities/releases/tag/3.0.0) release has been tagged.
